"""Make Node.last_seen nullable

Revision ID: 0b944542ccd8
Revises: 005
Create Date: 2025-12-08 00:07:49.891245+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b944542ccd8"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make Node.last_seen nullable since nodes from contact sync
    # haven't actually been "seen" on the mesh yet
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.alter_column("last_seen", existing_type=sa.DATETIME(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert Node.last_seen to non-nullable
    # Note: This will fail if there are NULL values in last_seen
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.alter_column("last_seen", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###
