"""add user_profiles and user_profile_nodes tables

Revision ID: 72b6578ee3bf
Revises: a10dbca883a2
Create Date: 2026-04-29 21:52:04.028351+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "72b6578ee3bf"
down_revision: Union[str, None] = "a10dbca883a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("callsign", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_profiles_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "user_profile_nodes",
        sa.Column("user_profile_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("adopted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profiles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_profile_id", "node_id"),
        sa.UniqueConstraint("node_id", name="uq_user_profile_nodes_node_id"),
    )
    with op.batch_alter_table("user_profile_nodes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_profile_nodes_node_id", ["node_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile_nodes", schema=None) as batch_op:
        batch_op.drop_index("ix_user_profile_nodes_node_id")

    op.drop_table("user_profile_nodes")
    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_profiles_user_id"))

    op.drop_table("user_profiles")
    # ### end Alembic commands ###
