"""add path_len to event_observers

Revision ID: a10dbca883a2
Revises: b1c2d3e4f5a6
Create Date: 2026-04-26 10:52:09.664958+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a10dbca883a2"
down_revision: Union[str, None] = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_observers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("path_len", sa.Integer(), nullable=True))
        batch_op.drop_constraint(
            batch_op.f("uq_event_receivers_hash_node"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_event_observers_hash_node", ["event_hash", "observer_node_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_observers", schema=None) as batch_op:
        batch_op.drop_constraint("uq_event_observers_hash_node", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_event_receivers_hash_node"),
            ["event_hash", "observer_node_id"],
        )
        batch_op.drop_column("path_len")

    # ### end Alembic commands ###
