"""add raw_packets table

Revision ID: e9f0c4079540
Revises: 20260610_1200
Create Date: 2026-06-12 19:47:12.406423+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e9f0c4079540"
down_revision: Union[str, None] = "20260610_1200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_packets",
        sa.Column("observer_node_id", sa.String(), nullable=True),
        sa.Column("packet_hash", sa.String(length=32), nullable=True),
        sa.Column("raw_hex", sa.Text(), nullable=True),
        sa.Column("packet_type", sa.Integer(), nullable=True),
        sa.Column("payload_type", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("channel_idx", sa.Integer(), nullable=True),
        sa.Column("source_pubkey_prefix", sa.String(length=12), nullable=True),
        sa.Column("route_type", sa.String(length=20), nullable=True),
        sa.Column("path_len", sa.Integer(), nullable=True),
        sa.Column("snr", sa.Float(), nullable=True),
        sa.Column("decoded", sa.JSON(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observer_node_id"], ["nodes.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_packets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_packets_channel_idx"), ["channel_idx"], unique=False
        )
        batch_op.create_index(
            "ix_raw_packets_channel_idx_received_at",
            ["channel_idx", "received_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_raw_packets_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            "ix_raw_packets_event_type_received_at",
            ["event_type", "received_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_raw_packets_observer_node_id"),
            ["observer_node_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_raw_packets_packet_hash"), ["packet_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_packets_packet_type"), ["packet_type"], unique=False
        )
        batch_op.create_index(
            "ix_raw_packets_received_at", ["received_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_packets_source_pubkey_prefix"),
            ["source_pubkey_prefix"],
            unique=False,
        )
        batch_op.create_index(
            "ix_raw_packets_source_pubkey_prefix_received_at",
            ["source_pubkey_prefix", "received_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_packets", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_packets_source_pubkey_prefix_received_at")
        batch_op.drop_index(batch_op.f("ix_raw_packets_source_pubkey_prefix"))
        batch_op.drop_index("ix_raw_packets_received_at")
        batch_op.drop_index(batch_op.f("ix_raw_packets_packet_type"))
        batch_op.drop_index(batch_op.f("ix_raw_packets_packet_hash"))
        batch_op.drop_index(batch_op.f("ix_raw_packets_observer_node_id"))
        batch_op.drop_index("ix_raw_packets_event_type_received_at")
        batch_op.drop_index(batch_op.f("ix_raw_packets_event_type"))
        batch_op.drop_index("ix_raw_packets_channel_idx_received_at")
        batch_op.drop_index(batch_op.f("ix_raw_packets_channel_idx"))

    op.drop_table("raw_packets")
    # ### end Alembic commands ###
