"""add description and url to user_profiles

Revision ID: d7a9bbe85a9e
Revises: a7eaa878e58b
Create Date: 2026-05-02 22:24:29.035729+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d7a9bbe85a9e"
down_revision: Union[str, None] = "a7eaa878e58b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("url", sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profiles", schema=None) as batch_op:
        batch_op.drop_column("url")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
