"""add packet_hash to messages and advertisements

Revision ID: e8eb47c49062
Revises: e9f0c4079540
Create Date: 2026-06-12 21:11:17.664733+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e8eb47c49062"
down_revision: Union[str, None] = "e9f0c4079540"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("advertisements", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("packet_hash", sa.String(length=32), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_advertisements_packet_hash"), ["packet_hash"], unique=False
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("packet_hash", sa.String(length=32), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_messages_packet_hash"), ["packet_hash"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_packet_hash"))
        batch_op.drop_column("packet_hash")

    with op.batch_alter_table("advertisements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_advertisements_packet_hash"))
        batch_op.drop_column("packet_hash")

    # ### end Alembic commands ###
